services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
